url: http://venth.github.io
title: Artur Krysiak Notebook
tagline: Notebook
description: Nice place to memorize learnt knowledge
paginate: 5

# Handling Reading
safe:         false
include:      [".htaccess", "tags.html"]
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - _docker
  - docker-compose.yml
  - .jekyll-metadata
keep_files:   [".git", ".svn", ".gitmodules"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins
repository: git@github.com:venth/venth.github.io.git
whitelist: []
plugins:
  - jekyll-paginate
  - jekyll-postfiles
  - kramdown
  - jekyll-watch
  - jekyll/tagging

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: /posts/:year/:month/:day/:title.html
paginate_path: /page/:num
timezone:      null

quiet: true
future: false
