url: http://venth.github.io
title: Artur Krysiak Notebook
tagline: Notebook
description: Nice place to memorize learnt knowledge
paginate: 5

# Handling Reading
safe:         false
include:      [".htaccess", "tags.html"]
exclude:      [Gemfile, Gemfile.lock, LICENSE.md]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins
whitelist: []
gems: [jekyll-paginate, jekyll-watch, kramdown]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: /posts/:year/:month/:day/:title.html
paginate_path: /page:num
timezone:      null

quiet:    false
future: true
